---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# but

<!-- badges: start -->
<!-- badges: end -->

The goal of but is to allow users to easily edit existing functions to suit their specific needs.
Edit the formals of a function and apply additional processing to its output.

## Installation

You can install the development version of but from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("hrryt/but")
```

## Examples

```{r}
library(but)

# supply default arguments to read.table
read.csv |> but(stringsAsFactors = TRUE, strip.white = TRUE)

`+` #primitive
double <- `+` |> but(e2 = e1)
double(4)

start_repeats <- grepl |> but( #create new argument n
  x = , n = 2, pattern = sprintf("^%s{%i}", substr(x, 1, 1), n),
  .first = TRUE
)
start_repeats("hhi", 3)
start_repeats("Hhello", ignore.case = TRUE)

# an argument that references .out
(slapply <- lapply |> but(.out |> simplify2array()))
3:9 |> slapply(seq) |> slapply(fivenum, na.rm = FALSE)
cor_dist <- cor |> but({
  dd <- as.dist((1 - .out)/2)
  plot(hclust(dd))
  dd
})
cor_dist(USJudgeRatings, method = "spearman") |> round(2)

but(lm) # lm(weights = weights) will error if run
# use .wrap = FALSE to avoid the pitfalls of
# non-standard evaluation in the body of .f
lm_for_pipe <- lm |> but(data = , .first = TRUE, .wrap = FALSE)
mtcars |> subset(cyl == 4) |> lm_for_pipe(mpg ~ disp)

# use .pass_all = FALSE to avoid passing
# extra arguments to the dots of .f
outer |> but(
  n = , X = seq_len(n), Y = X,
  .first = TRUE, .pass_all = FALSE
) |> print() |> do(4) |> print()

(numbers <- seq(1, 3, 0.5))
but(split, f = floor(x))(numbers) #equivalent to using pipe

#dangerous; see warning
`last<-` <- but(`[[<-`, x = , i = length(x), value = )
last(numbers) <- 0
numbers
```
